name: Lint

on:
  pull_request:
  push:
    branches:
      - '**' # matches every branch

jobs:
  lint_and_typecheck:
    name: Lint and Typecheck
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Install pnpm
        uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6

      - name: Setup Node.js
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 24

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline --store-dir /tmp/pnpm-store

      - name: Run lint
        run: pnpm run lint

      - name: Run unit tests
        run: pnpm test
